default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: psd-call-jsa-dev_development

test:
  <<: *default
  database: psd-call-jsa-dev_test
